#!/bin/sh
export EDITOR=nvim
export _JAVA_AWT_WM_NONREPARENTING=1

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4


if [[ $(xrandr -q | grep 'HDMI-1 connected') ]]; then
    xrandr --output eDP-1 --off 
    xrandr --output HDMI-1 --primary --mode 3840x2160 --scale 0.9999x0.9999
    xrandr --output HDMI-1 --auto --pos 0x0
    xrandr --output eDP-1 --auto --pos 0x0 --scale 2x2
    bspc monitor HDMI-1 --remove 
fi

bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#e6c384"
bspc config normal_border_color "#727169"
bspc config border_width 2 

bspc rule -a mpv state=floating sticky=on center=true
bspc rule -a 'Xdm-app' state=floating center=true
bspc rule -a ':yad' state=floating
bspc rule -a ':Nitrogen' state=floating center=true
bspc rule -a ':Blueman-manager' state=floating center=true
bspc rule -a '*:*:Picture-in-Picture' state=floating sticky=on
bspc rule -a ":KeePassXC" state=floating center=true

# Run on startup only
[ "$1" = 0 ] && {
        nitrogen --restore &
        xsetroot -cursor_name left_ptr &
        nm-applet --indicator &
        udiskie --tray &
        picom &
        polybar &
        keepassxc &
        if [ -e "$HOME/.config/sxhkd/lock.sh" ]; then
            xss-lock -- $HOME/.config/sxhkd/lock.sh
        fi
}
